site_name: mkdocs-pydantic
theme:
  name: material
  features:
    - navigation.indexes
    - navigation.expand
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav:
  - index.md
  - 'pydantic:::mkdocs_pydantic_examples.TwoLevels'
  - Base Directory:
      - SomeAlias: 'pydantic:::mkdocs_pydantic_examples.ThreeLevels'
  - 'pydantic:::mkdocs_pydantic_examples.SingleLevel'
  - Static Example:
      - static/index.md

markdown_extensions:
  - attr_list
  - md_in_html

plugins:
  - pydantic
  - mkdocstrings:
      handlers:
        python:
          options:
            separate_signatures: true
            show_signature_annotations: true
            members_order: source
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true
            signature_crossrefs: true
