site_name: mkdocs-pydantic
theme:
  name: readthedocs
nav:
  - Example:
      - pydantic:::mkdocs_pydantic_example.Settings
      - other/index.md
  - Example2:
      - Subdirectory:
        - pydantic:::mkdocs_pydantic_example.Settings
        - other/index.md
      - Other:
          - other/index.md
  - pydantic:::mkdocs_pydantic_example.Settings
  - Static Example:
      - static/index.md

markdown_extensions:
  - attr_list
  - md_in_html

plugins:
  - pydantic
  - mkdocstrings:
      handlers:
        python:
          options:
            separate_signatures: true
            show_signature_annotations: true
            members_order: source
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true
            signature_crossrefs: true