site_name: mkdocs-pydantic
theme:
  name: material
  features:
    - navigation.indexes
    - navigation.expand
nav:
  - index.md
  - TwoLevels: 'pydantic:::mkdocs_pydantic_examples.TwoLevels'
  - Base Directory:
      - ThreeLevels: 'pydantic:::mkdocs_pydantic_examples.ThreeLevels'
  - pydantic:::mkdocs_pydantic_examples.SingleLevel
  - Static Example:
      - static/index.md

markdown_extensions:
  - attr_list
  - md_in_html

plugins:
  - pydantic
  - mkdocstrings:
      handlers:
        python:
          options:
            separate_signatures: true
            show_signature_annotations: true
            members_order: source
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true
            signature_crossrefs: true
