name: Docs
on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:
permissions:
  contents: read

jobs:
  lint:
    concurrency:
      group: docs-${{ github.event_name == 'push' && github.run_number || github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup environement
        uses: ./.github/actions/setup
        with:
          install-extras: 'docs'

      - name: Docs
        run: mkdocs build --strict

      - name: Upload docs as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: Docs
          path: site/
          retention-days: 14
